using 'main.bicep'

param location = 'centralindia'
param appServicePlanName = 'asp-webapps-dev'
param skuName = 'B1'
param skuTier = 'Basic'
param webAppNames = [
  'Glas-app-01'
  'Glas-app-02'
  'Glas-app-03'
  'Glas-app-04'
]
param keyVaultName = 'kv-webapps-dev01'
param containerImage = 'staticsite:latest'
param acrName = 'acrglasdev01'
param acrSku = 'Basic'
param staticWebAppName = 'swa-glas-dev'
param staticWebAppLocation = 'eastus2'
param staticWebAppSku = 'Free'
param staticWebAppProvider = 'DevOps'
param repositoryUrl = 'https://dev.azure.com/your-org/your-project/_git/your-repo'
param branch = 'main'
param logAnalyticsWorkspaceName = 'law-glas-dev'
param appInsightsName = 'appi-glas-dev'
param vnetName = 'vnet-glas-dev'
param vnetAddressPrefix = '10.0.0.0/16'
param webAppSubnetName = 'snet-webapps'
param webAppSubnetPrefix = '10.0.1.0/24'
param privateEndpointSubnetName = 'snet-private-endpoints'
param privateEndpointSubnetPrefix = '10.0.2.0/24'
param cosmosAccountName = 'cosmos-glas-dev'
param privateEndpointName = 'pe-cosmos-glas-dev'
param privateDnsZoneName = 'privatelink.documents.azure.com'
